DEBUG - 2025-06-21 21:38:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 21:39:17 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 21:39:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 21:40:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 21:40:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 21:40:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-06-21 21:40:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 21:41:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 21:41:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 21:52:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 21:52:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tu_usuario'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'tu_usuario', Object(SensitiveParameterValue), 'nombre_bd', 3306, '', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 21:52:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 21:54:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 21:54:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tu_usuario'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'tu_usuario', Object(SensitiveParameterValue), 'ulises_ivan_mi\xC3...', 3306, '', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 21:54:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 22:06:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 22:07:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'tu_usuario'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'tu_usuario', Object(SensitiveParameterValue), 'ulises_ivan_mi\xC3...', 3306, '', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 22:07:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 22:10:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 22:11:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'uli'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'uli', Object(SensitiveParameterValue), 'ulises_ivan_mi\xC3...', 3306, '', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 22:11:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 22:19:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 22:19:42 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-06-21 22:19:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 22:19:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$3rRSWh1d5rGTN9qGkbWR8OPFPeOhCWZIuE09QxwrfVlE5gOm1r9ia\', \'2025-06-21 22:19:42\', \'2025-06-21 22:19:42\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$3rRSWh1d5rGTN9qGkbWR8OPFPeOhCWZIuE09QxwrfVlE5gOm1r9ia\', \'2025-06-21 22:19:42\', \'2025-06-21 22:19:42\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 22:19:42 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$3rRSWh1d5rGTN9qGkbWR8OPFPeOhCWZIuE09QxwrfVlE5gOm1r9ia\', \'2025-06-21 22:19:42\', \'2025-06-21 22:19:42\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$3rRSWh1d5rGTN9qGkbWR8OPFPeOhCWZIuE09QxwrfVlE5gOm1r9ia\', \'2025-06-21 22:19:42\', \'2025-06-21 22:19:42\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$3rRSWh1d5rGTN9qGkbWR8OPFPeOhCWZIuE09QxwrfVlE5gOm1r9ia\', \'2025-06-21 22:19:42\', \'2025-06-21 22:19:42\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 22:25:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 22:25:33 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-06-21 22:25:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 22:25:33 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$L2HBXnm5XEAbwDL.ijXpieqgMsPcA0Ym/eVPFbpuUxnF/Wn/9g.se\', \'2025-06-21 22:25:33\', \'2025-06-21 22:25:33\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$L2HBXnm5XEAbwDL.ijXpieqgMsPcA0Ym/eVPFbpuUxnF/Wn/9g.se\', \'2025-06-21 22:25:33\', \'2025-06-21 22:25:33\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 22:25:33 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$L2HBXnm5XEAbwDL.ijXpieqgMsPcA0Ym/eVPFbpuUxnF/Wn/9g.se\', \'2025-06-21 22:25:33\', \'2025-06-21 22:25:33\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$L2HBXnm5XEAbwDL.ijXpieqgMsPcA0Ym/eVPFbpuUxnF/Wn/9g.se\', \'2025-06-21 22:25:33\', \'2025-06-21 22:25:33\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$L2HBXnm5XEAbwDL.ijXpieqgMsPcA0Ym/eVPFbpuUxnF/Wn/9g.se\', \'2025-06-21 22:25:33\', \'2025-06-21 22:25:33\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-06-21 22:29:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-21 22:30:22 --> mysqli_sql_exception: Duplicate entry 'unnisemai@gmail.com' for key 'email' in C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ProT2_45526629\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ProT2_45526629\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ProT2_45526629\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ProT2_45526629\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ProT2_45526629\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ProT2_45526629\app\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
#10 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\ProT2_45526629\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ProT2_45526629\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ProT2_45526629\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-06-21 22:30:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'unnisemai@gmail.com' for key 'email'
[Method: POST, Route: usuario/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 22:30:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'unnisemai@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$YGQe72Tb7zCknXPbYHpEUeMbsBiz6niyiOKzx0FvDE/Z.htbiKSve\', \'2025-06-21 22:30:22\', \'2025-06-21 22:30:22\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$YGQe72Tb7zCknXPbYHpEUeMbsBiz6niyiOKzx0FvDE/Z.htbiKSve\', \'2025-06-21 22:30:22\', \'2025-06-21 22:30:22\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 22:30:22 --> [Caused by] mysqli_sql_exception: Duplicate entry 'unnisemai@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$YGQe72Tb7zCknXPbYHpEUeMbsBiz6niyiOKzx0FvDE/Z.htbiKSve\', \'2025-06-21 22:30:22\', \'2025-06-21 22:30:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$YGQe72Tb7zCknXPbYHpEUeMbsBiz6niyiOKzx0FvDE/Z.htbiKSve\', \'2025-06-21 22:30:22\', \'2025-06-21 22:30:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (\'ulises ivan\', \'unnisemai@gmail.com\', \'$2y$10$YGQe72Tb7zCknXPbYHpEUeMbsBiz6niyiOKzx0FvDE/Z.htbiKSve\', \'2025-06-21 22:30:22\', \'2025-06-21 22:30:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre`, `email`, `contraseña`, `created_at`, `updated_at`) VALUES (:nombre:, :email:, :contraseña:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\UsuarioController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
